/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AttendanceIndexImport } from './routes/attendance/index'
import { Route as AttendanceIdImport } from './routes/attendance/$id'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AttendanceIndexRoute = AttendanceIndexImport.update({
  path: '/attendance/',
  getParentRoute: () => rootRoute,
} as any)

const AttendanceIdRoute = AttendanceIdImport.update({
  path: '/attendance/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/attendance/$id': {
      id: '/attendance/$id'
      path: '/attendance/$id'
      fullPath: '/attendance/$id'
      preLoaderRoute: typeof AttendanceIdImport
      parentRoute: typeof rootRoute
    }
    '/attendance/': {
      id: '/attendance/'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AttendanceIdRoute,
  AttendanceIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/attendance/$id",
        "/attendance/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/attendance/$id": {
      "filePath": "attendance/$id.tsx"
    },
    "/attendance/": {
      "filePath": "attendance/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
